dependencies:
  - numpy
  - h5py
  - matplotlib
  - scipy
  - six
  - pip
  - pip:
     - "--editable=git+https://github.com/lkilcher/pyDictH5.git@master#egg=pyDictH5"

  # For building docs
  - sphinx
  - numpydoc

  # For running tests
  # yes I know nose is old, I'm working on moving to pytest, but I'm not there yet
  - nose
